/*
 * This source file was generated by the Gradle 'init' task
 */
package calculator1;

import main.java.calculator1.BasicCalculator;
import main.java.calculator1.Calculator;
import main.java.calculator1.SceintificCal;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

         Calculator calc = new BasicCalculator(10,5);
        // calc.add();
        // calc.multiply();
        calc.subtraction();


        //  Calculator calc1 = new SceintificCal(10,20,30);
        //  calc1.add();
        //  calc1.multiply();
        //  calc1.subtraction();
    }
}
